import sys 
from PySide2.QtWidgets import *
from PySide2.QtCore import *
from PySide2.QtGui import *

class SignUpWidget(QWidget):
    def __init__(self):
        QWidget.__init__(self,None)
        self.setColor()
        self.username_label = QLabel("Username: ")
        self.username_label.setFont(QFont("Century Gothic", 11,QFont.Bold))
        self.username_lineEdit = QLineEdit()
        self.password_label = QLabel("Password: ")
        self.password_label.setFont(QFont("Century Gothic", 11,QFont.Bold))
        self.password_lineEdit = QLineEdit()
        self.confirm_pass_label = QLabel("Confirm Password: ")
        self.confirm_pass_label.setFont(QFont("Century Gothic", 11,QFont.Bold))
        self.username_label.setStyleSheet("color: white")
        self.password_label.setStyleSheet("color: white")
        self.confirm_pass_label.setStyleSheet("color:white")
        self.confirm_pass_lineEdit = QLineEdit()
        self.signup_btn = QPushButton("SIGN UP")
        self.signup_btn.setStyleSheet("background-color:rgb(250,231,110);color:rgb(49,68,111)")
        self.signup_btn.clicked.connect(self.signUP)
        self.isHasUser = False
        self.signup_btn.setFont(QFont("Moon", 10,QFont.Bold))
        self.signup_btn.setFixedSize(100,30)
        self.signup_layout = QFormLayout()
        self.grid_signup_layout = QGridLayout()
        self.username_label.setContentsMargins(30,30,10,15)
        self.username_lineEdit.setContentsMargins(0,30,30,15)
        self.signup_layout.addRow(self.username_label, self.username_lineEdit)
        self.password_label.setContentsMargins(30,0,10,15)
        self.password_lineEdit.setContentsMargins(0,0,30,15)
        self.signup_layout.addRow(self.password_label, self.password_lineEdit)
        self.confirm_pass_label.setContentsMargins(30,0,10,20)
        self.confirm_pass_lineEdit.setContentsMargins(0,0,30,20)
        self.signup_layout.addRow(self.confirm_pass_label,self.confirm_pass_lineEdit)
        self.grid_signup_layout.addLayout(self.signup_layout,0,0)
        self.grid_signup_layout.addWidget(self.signup_btn,1,0,1,1,Qt.AlignCenter)
        self.setLayout(self.grid_signup_layout)
    def setColor(self):
        self.pal = QPalette()
        self.setAutoFillBackground(True)
        self.pal.setColor(QPalette.Window,QColor(82,113,159))
        self.setPalette(self.pal)
    def signUP(self):
        if(self.isHasUser == True):
            print("Success Sign Up")
        else:
            dialog = QDialog(self)
            dialog.setWindowTitle("Error")
            layout = QVBoxLayout()
            errMessage = QLabel(self)
            errMessage.setText("This number is already registered")
            close = QPushButton('Close')
            close.clicked.connect(dialog.close)
            layout.addWidget(errMessage)
            layout.addWidget(close)
            dialog.setLayout(layout)
            dialog.show()
            print("Error Message")
class LoginWidget(QWidget):
    def __init__(self):
        QWidget.__init__(self,None)
        self.setColor()
        self.username_label = QLabel("Username: ")
        self.username_label.setFont(QFont("Century Gothic", 11,QFont.Bold))
        self.username_lineEdit = QLineEdit()
        self.password_label = QLabel("Password: ")
        self.password_label.setFont(QFont("Century Gothic", 11,QFont.Bold))
        self.username_label.setStyleSheet("color: white")
        self.password_label.setStyleSheet("color: white")
        self.password_lineEdit = QLineEdit()
        self.login_btn = QPushButton("LOG IN")
        self.login_btn.clicked.connect(self.login)
        self.login_btn.setFixedSize(100,30)
        self.grid_login_layout = QGridLayout()
        self.login_layout = QFormLayout()
        self.username_label.setContentsMargins(30,50,10,25)
        self.username_lineEdit.setContentsMargins(0,50,30,25)
        self.login_layout.addRow(self.username_label, self.username_lineEdit)
        self.password_label.setContentsMargins(30,0,10,20)
        self.password_lineEdit.setContentsMargins(0,0,30,20)
        self.login_layout.addRow(self.password_label, self.password_lineEdit)
        self.login_btn.setFont(QFont("Moon", 10,QFont.Bold))
        self.login_btn.setStyleSheet("background-color:rgb(250,231,110);color:rgb(49,68,111)")
        self.grid_login_layout.addLayout(self.login_layout,0,0)
        self.grid_login_layout.addWidget(self.login_btn,1,0,1,1,Qt.AlignCenter)
        self.setLayout(self.grid_login_layout)
    def setColor(self):
        self.pal = QPalette()
        #self.color_white = QColor((196,196,196))
        self.setAutoFillBackground(True)
        self.pal.setColor(QPalette.Window,QColor(82,113,159))
        self.setPalette(self.pal)
    def login(self):
        print("LOG IN success")
class Login_Signin_Page(QWidget):
    def __init__(self):
        QWidget.__init__(self,None)
        self.tabWidget = QTabWidget()
        #self.tabWidget.setStyleSheet("color: rgb(82,113,159)")
        #self.tabWidget.setTabTextColor(QColor(255,255,222))
        self.login= LoginWidget()
        #self.login.login_btn.setGeometry(0,0,49,30)
        self.tabWidget.setFixedSize(313,263)
        self.signup = SignUpWidget()
        self.tabWidget.setFont(QFont("Century Gothic", 8))
        self.tabWidget.addTab(self.login, "Log in")
        self.tabWidget.addTab(self.signup, "Sign up")
        self.setWindowTitle("Bello project")
        self.project_name_label = QLabel("Bello")
        self.login_signup_layout = QVBoxLayout()
        self.setContentsMargins(150,60,20,140)
        self.project_name_label.setContentsMargins(133,0,0,25)
        self.login_signup_layout.addWidget(self.project_name_label)
        self.login_signup_layout.addWidget(self.tabWidget)
        self.project_name_label.setFont(QFont("Moon", 24,QFont.Bold))
        self.setLayout(self.login_signup_layout)
        self.icon_Bello = QPixmap("images/iconBello.png")

    def paintEvent(self,e):
        paint = QPainter()
        self.pal = QPalette()
        self.setAutoFillBackground(True)
        self.pal.setColor(QPalette.Window,QColor(255,255,255))

        self.setPalette(self.pal)
        paint.begin(self)
        paint.setPen(QColor(248,215,60))
        paint.setBrush(QColor(248,215,60))
        paint.drawEllipse(QPoint(20,350), 125, 125)
        paint.drawEllipse(QPoint(620,140), 125, 125)
        '''paint.setPen(QColor(255,160,122))
        paint.setBrush(QColor(255,160,122))
        paint.drawPolygon([QPoint(80,60),QPoint(200,110),QPoint(150,200),])
        paint.drawPolygon([QPoint(430,300),QPoint(600,100),QPoint(500,400),])'''
        paint.drawPixmap(QRect(245,60,40,40),self.icon_Bello)
        paint.end()
    
def main():
    app = QApplication(sys.argv)
    w = Login_Signin_Page()
    w.setFixedSize(640, 480)
    w.show()
    return app.exec_()
if __name__ == "__main__":
    sys.exit(main())